//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Collection.DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int InvoiceId { get; set; }
        public Nullable<int> InvoiceNo { get; set; }
        public System.DateTime IssueDate { get; set; }
        public decimal Amount { get; set; }
        public System.DateTime CollectDate { get; set; }
        public System.DateTime ActCollectDate { get; set; }
        public Nullable<bool> Suspended { get; set; }
        public Nullable<bool> Collected { get; set; }
        public Nullable<int> Cus_id { get; set; }
    
        public virtual Comment Comment { get; set; }
        public virtual Customer Customer { get; set; }
    }
}
